/*************************************************************************
 * SPDX-FileCopyrightText: Copyright (c) 2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-FileCopyrightText: Copyright (c) 2023, Meta Platforms, Inc. and affiliates.
 * SPDX-License-Identifier: Apache-2.0 and BSD-3
 *
 * See LICENSE.txt for more license information
 *************************************************************************/

/*
 * src/include/plugin/tuner/tuner_v5.h — Tuner v5 接口 [NVIDIA 插件接口/第三方]
 * ----------------------------------------------------------------------------
 * 外部调优器需实现的 v5 版本接口，含 NVL 域(NVLink 域)信息结构。
 */

#ifndef TUNER_V5_H_
#define TUNER_V5_H_

// NVL 域 information 结构体
typedef struct {
  int nNvlDomains;                    // number of NVLink domains
  int minRanksPerNvlDomain;           // minimum ranks across all NVLink domains
  int maxRanksPerNvlDomain;           // maximum ranks across all NVLink domains
} ncclNvlDomainInfo_v5_t;

#define NCCL_NUM_ALGORITHMS_V5 7 // Tree/Ring/CollNet*/PAT
#define NCCL_NUM_PROTOCOLS_V5 3 // Simple/LL/LL128
#define NCCL_NUM_HW_LINKS_V5 3
#define NCCL_NUM_COMPCAPS_V5 4
#define NCCL_NUM_TUNING_SCALES_V5 3

typedef struct {
  double baseLatencies[NCCL_NUM_ALGORITHMS_V5][NCCL_NUM_PROTOCOLS_V5];
  double hwLatencies[NCCL_NUM_HW_LINKS_V5][NCCL_NUM_ALGORITHMS_V5][NCCL_NUM_PROTOCOLS_V5];

  double llMaxBws[NCCL_NUM_COMPCAPS_V5][NCCL_NUM_TUNING_SCALES_V5];
  double perChMaxRingLL128Bws[NCCL_NUM_COMPCAPS_V5][NCCL_NUM_TUNING_SCALES_V5];
  double perChMaxTreeLL128Bws[NCCL_NUM_COMPCAPS_V5][NCCL_NUM_TUNING_SCALES_V5];
  double perChMaxTreeBws[NCCL_NUM_COMPCAPS_V5][NCCL_NUM_TUNING_SCALES_V5];
  double perChMaxNVLSTreeBws[NCCL_NUM_COMPCAPS_V5][NCCL_NUM_TUNING_SCALES_V5];

} ncclTunerConstants_v5_t;

// API to be implemented by 外部 tuner
typedef struct {
  // Name 的 tuner
  const char* name;

  // Initializes tuner 状态.
  // 输入参数：
  //   - commId: 通信器 identifier
  //   - nRanks: 数量： ranks 入 当前的 通信器. 每个 通信器 初始化 its 自身的 tuner.
  //   - nNodes: 数量： 节点 入 当前的 通信器.
  //   - logFunction: a logFunction 可以 useful to integrate logging 与 ... 一起 NCCL core.
  //   - nvlDomainInfo: NVL 域 information 结构体
  // 输出参数：
  //   - 上下文: tuner 上下文 object
  // 输入/输出:
  //   - 常量：调优器常量
  ncclResult_t (*init)(void** ctx, uint64_t commId, size_t nRanks, size_t nNodes, ncclDebugLogger_t logFunction,
                       ncclNvlDomainInfo_v5_t* nvlDomainInfo, ncclTunerConstants_v5_t* constants);

  // Gets 信息 (algo, protocol, 数量： ctas 并且 线程) for a 给定的 集合.
  // 输入参数：
  //   - 上下文: tuner 上下文 object
  //   - collType: 集合 类型 , e.g., 全规约, 全收集…
  //   - nBytes: 集合 大小 入 字节
  //   - numPipeOps: 数量： 操作 在 ... 中 组
  //   - numAlgo: 数量： 算法 入 collCostTable
  //   - numProto: 数量： protocols 入 collCostTable
  //   - regBuff: can 寄存器 用户 缓冲区
  //
  // 输出参数：
  //   - nChannels: 数量： 通道 (因此 SMs) to be 已使用.
  //
  // 输入输出：
  //   - collCostTable: 集合 代价 table, generated by NCCL core, containing algo|proto|time entries for collType.
  //                    NCCL core sets ignored algo/proto 代价 table entries to -1.0 (NCCL_ALGO_PROTO_IGNORE).
  //
  // 若 getCollInfo() 执行 不 返回 ncclSuccess, NCCL will 回退到 the
  // 默认 tuning 为了 给定的 集合.
  // 也, the 插件 is 允许的 to 不 设置 任意 输出, 或者 设置 仅 the
  // 算法 并且 protocol, 但 不 仅 the 算法 或者 仅 the protocol.
  // Unset 字段 将会 设置 automatically by NCCL.
  ncclResult_t (*getCollInfo)(void* context, ncclFunc_t collType, size_t nBytes, int numPipeOps, float** collCostTable,
                              int numAlgo, int numProto, int regBuff, int* nChannels);

  // Terminates the 插件 并且 cleans up 任意 resources 那个 the 插件 已分配.
  // 上下文: tuner 上下文 object
  ncclResult_t (*finalize)(void* context);
} ncclTuner_v5_t;

#endif
