/*************************************************************************
 * Copyright (c) 2023, NVIDIA CORPORATION. All rights reserved.
 * Copyright (c) 2023, Meta Platforms, Inc. and affiliates.
 *
 * See LICENSE.txt for license information
 ************************************************************************/

/*
 * src/include/plugin/tuner/tuner_v6.h — Tuner v6 接口 [NVIDIA 插件接口/第三方]
 * ----------------------------------------------------------------------------
 * 外部调优器需实现的 v6 版本接口（继承并扩展 v5）。
 */

#ifndef TUNER_V6_H_
#define TUNER_V6_H_

#include "tuner_v5.h"

// V6 constants 并且 NVL 域 信息 are 相同 as V5 - 无 minChunkSize table 已需要
// 块 大小 overrides are handled via the getChunkSize 回调函数 改为
typedef ncclTunerConstants_v5_t ncclTunerConstants_v6_t;
typedef ncclNvlDomainInfo_v5_t ncclNvlDomainInfo_v6_t;

// API to be implemented by 外部 tuner
typedef struct {
  // Name 的 tuner
  const char* name;

  // Initializes tuner 状态.
  // 输入参数：
  //   - commId: 通信器 identifier
  //   - nRanks: 数量： ranks 入 当前的 通信器. 每个 通信器 初始化 its 自身的 tuner.
  //   - nNodes: 数量： 节点 入 当前的 通信器.
  //   - logFunction: a logFunction 可以 useful to integrate logging 与 ... 一起 NCCL core.
  //   - nvlDomainInfo: NVL 域 information 结构体
  // 输出参数：
  //   - 上下文: tuner 上下文 object
  // 输入/输出:
  //   - 常量：调优器常量
  ncclResult_t (*init)(void** ctx, uint64_t commId, size_t nRanks, size_t nNodes, ncclDebugLogger_t logFunction,
                       ncclNvlDomainInfo_v6_t* nvlDomainInfo, ncclTunerConstants_v6_t* constants);

  // Gets 信息 (algo, protocol, 数量： ctas 并且 线程) for a 给定的 集合.
  // 输入参数：
  //   - 上下文: tuner 上下文 object
  //   - collType: 集合 类型 , e.g., 全规约, 全收集…
  //   - nBytes: 集合 大小 入 字节
  //   - numPipeOps: 数量： 操作 在 ... 中 组
  //   - numAlgo: 数量： 算法 入 collCostTable
  //   - numProto: 数量： protocols 入 collCostTable
  //   - regBuff: can 寄存器 用户 缓冲区
  //
  // 输出参数：
  //   - nChannels: 数量： 通道 (因此 SMs) to be 已使用.
  //
  // 输入输出：
  //   - collCostTable: 集合 代价 table, generated by NCCL core, containing algo|proto|time entries for collType.
  //                    NCCL core sets ignored algo/proto 代价 table entries to -1.0 (NCCL_ALGO_PROTO_IGNORE).
  //
  // 若 getCollInfo() 执行 不 返回 ncclSuccess, NCCL will 回退到 the
  // 默认 tuning 为了 给定的 集合.
  // 也, the 插件 is 允许的 to 不 设置 任意 输出, 或者 设置 仅 the
  // 算法 并且 protocol, 但 不 仅 the 算法 或者 仅 the protocol.
  // Unset 字段 将会 设置 automatically by NCCL.
  ncclResult_t (*getCollInfo)(void* context, ncclFunc_t collType, size_t nBytes, int numPipeOps, float** collCostTable,
                              int numAlgo, int numProto, int regBuff, int* nChannels);

  // Terminates the 插件 并且 cleans up 任意 resources 那个 the 插件 已分配.
  // 上下文: tuner 上下文 object
  ncclResult_t (*finalize)(void* context);

  // Allows the tuner 插件 to override the 块 大小 computed by NCCL.
  // 该函数 is 可选 - 若 NULL, NCCL's computed 块 大小 用于.
  // 输入参数：
  //   - 上下文: tuner 上下文 object
  //   - collType: 集合 类型, e.g., 全规约, 全收集...
  //   - nBytes: 集合 大小 入 字节
  //   - algo: selected 算法 (NCCL_ALGO_*)
  //   - proto: selected protocol (NCCL_PROTO_*)
  //   - nChannels: 数量： 通道 being 已使用
  // 输入输出：
  //   - chunkSize: 指针 到 块 大小 computed by NCCL. The 插件 can
  //                读取 并且 modify 该值. NCCL will clamp the 结果 to
  //                最大 允许的 块 大小 基于 缓冲区 约束.
  ncclResult_t (*getChunkSize)(void* context, ncclFunc_t collType, size_t nBytes, int algo, int proto, int nChannels,
                               size_t* chunkSize);
} ncclTuner_v6_t;

#endif
